CREATE DATABASE dygest IF NOT EXISTS;

USE dygest;

CREATE TABLE summary (id MEDIUMINT NOT NULL AUTO_INCREMENT, title VARCHAR(1024) NOT NULL, body TEXT NOT NULL, time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
