CREATE DATABASE IF NOT EXISTS dygest;

USE dygest;

CREATE TABLE stories (id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY, title VARCHAR(1024) NOT NULL, body TEXT NOT NULL, time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
